import {
  Alert,
  Card,
  Calendar,
  Caption,
  Checkbox,
  CircleButton,
  Button,
  DatePicker,
  DialogBox,
  EmptyState,
  FormSection,
  Grid,
  Heading,
  InputWrapper,
  Label,
  ListDescription,
  ListExtraLeft,
  ListExtraRight,
  ListTitle,
  Logo,
  Module,
  NavBar,
  NavItem,
  Page,
  Paragraph,
  Sidebar,
  SidebarModule,
  Skeleton,
  TextInput,
  Toolbar,
  ToolbarItem,
  Chip,
  MultiSelect,
  CustomBaseColors,
  CustomColors,
  CustomSupport,
  CustomTypography,
  createTheme,
} from '../../../dist'

const baseColors: CustomBaseColors = {}
const colors: CustomColors = {}
const typography: CustomTypography = {}
const support: CustomSupport = { BORDER_RADIUS: '0' }

export const theme = createTheme(
  [
    Alert,
    Button,
    Caption,
    Calendar,
    Card,
    Chip,
    Checkbox,
    CircleButton,
    DatePicker,
    DialogBox,
    EmptyState,
    FormSection,
    Grid,
    Heading,
    InputWrapper,
    Label,
    ListDescription,
    ListExtraLeft,
    ListExtraRight,
    ListTitle,
    Logo,
    Module,
    MultiSelect,
    NavBar,
    NavItem,
    Page,
    Paragraph,
    Sidebar,
    SidebarModule,
    Skeleton,
    TextInput,
    Toolbar,
    ToolbarItem,
  ],
  {
    baseColors,
    colors,
    typography,
    support,
  },
)
